trigger:
- none

pool: 
 name: agent1

stages:
- stage: Terraform_init
  displayName: "Terrafrom init"
  jobs:
  - job: terraforminit
    steps:
    - task: TerraformInstaller@1
      inputs:
       terraformVersion: 'latest'

