trigger:
- none

pool: 
 name: agent1

stages:
- stage: scan
  displayName: "tflint scan"
  jobs:
  - job: tflint_scan
    continueOnError: true
    steps:
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: 'tflint --chdir=$(System.DefaultWorkingDirectory) --recursive /format:tflient.json'

- stage: Terraform_init
  displayName: "Terrafrom init"
  jobs:
  - job: terraforminit
    steps:
    - task: TerraformInstaller@1
      inputs:
       terraformVersion: 'latest'
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)\dev'
        backendServiceArm: 'svc'
        backendAzureRmStorageAccountName: 'storage5522'
        backendAzureRmContainerName: 'cont1'
        backendAzureRmKey: 'terraform.tfstate'
- stage: Terrafrom_plan
  displayName: "Terrafrom plan"
  jobs:
  - job: terraformplan
    steps:
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)\dev'
        backendServiceArm: 'svc'
        backendAzureRmStorageAccountName: 'storage5522'
        backendAzureRmContainerName: 'cont1'
        backendAzureRmKey: 'terraform.tfstate'
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)\dev'
        environmentServiceNameAzureRM: 'svc'

- stage: Terrafrom_apply
  displayName: "Terrafrom apply"
  jobs:
  - job: waitForValidation
    displayName: Manual validation
    pool: server
    timeoutInMinutes: 90
    steps: 
    - task: ManualValidation@1
      inputs:
        notifyUsers: 'ab@.com'
        instructions: 'verify after aproove'

  
  - job: terraformapply
    dependsOn: waitForValidation

    steps:
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)\dev'
        backendServiceArm: 'svc'
        backendAzureRmStorageAccountName: 'storage5522'
        backendAzureRmContainerName: 'cont1'
        backendAzureRmKey: 'terraform.tfstate'
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)\dev'
        environmentServiceNameAzureRM: 'svc'

- stage: Terrafrom_destroy
  displayName: "Terrafrom destroy"
  jobs:
  - job: waitForValidation
    displayName: Manual validation
    pool: server
    timeoutInMinutes: 90
    steps: 
    - task: ManualValidation@1
      inputs:
        notifyUsers: 'ab@.com'
        instructions: 'verify after aproove'

  
  - job: terraformdestroy
    dependsOn: waitForValidation

    steps:
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)\dev'
        backendServiceArm: 'svc'
        backendAzureRmStorageAccountName: 'storage5522'
        backendAzureRmContainerName: 'cont1'
        backendAzureRmKey: 'terraform.tfstate'
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'destroy'
        workingDirectory: '$(System.DefaultWorkingDirectory)\dev'
        environmentServiceNameAzureRM: 'svc'


